### ISSUE TITLE
Anonfiles Went Down (Links Deprecated)

### ISSUE THREAD

**Issue by x0meko** [c-um/Red-Team-Tools#1]
Hey, I'm hoping you've still got the files themselves laying around somewhere on your machine since anonfiles unfortunately was shut down recently (and therefore the links no longer work).

Would appreciate any reuploads :)

**Comment by JassonAvila** [comment]
Any luck?

**Comment by Ixve** [comment]
I will update this later tomorrow - no time at the moment.

**Comment by Ixve** [comment]
Updated C2/RATs list with working links using catbox.moe provider - if it goes down tell me.

Will update the rest of the tools later tomorrow.

**Comment by Ixve** [comment]
If anyone in this issue is interested, *everything* has been updated as of 01/27/2024
